# Indexação e fatiamento (slicing)

In [1]:
# Importando o NumPy
import numpy as np

In [2]:
# Cria um ndarray com 10 elementos entre 0 e 9
a1D = np.random.randint(0, 10, 10)
a1D

array([3, 7, 6, 4, 2, 9, 7, 3, 6, 1])

In [3]:
a2D = np.random.randint(1, 101, (4,5)) # Cria um ndarray de 4 linhas x 5 colunas com elementos entre 1 e 100
a2D

array([[24, 84, 82, 57, 76],
       [57, 77, 47, 55, 28],
       [49, 52, 44, 39, 47],
       [84, 90, 27, 43, 83]])

In [4]:
a3D = np.random.random((3,4,5)) # Cria um ndarray de 3 páginas x 4 linhas x 5 colunas com elementos entre 0 e 1
a3D

array([[[0.88720697, 0.14172453, 0.68358888, 0.53132012, 0.58597368],
        [0.06332662, 0.00480406, 0.30022844, 0.33106264, 0.93174487],
        [0.80329166, 0.05535711, 0.19428014, 0.15125549, 0.03183321],
        [0.07259996, 0.69920108, 0.14796289, 0.05212782, 0.9861232 ]],

       [[0.89658827, 0.26275716, 0.36136653, 0.72448043, 0.73187594],
        [0.8340891 , 0.13870417, 0.23590704, 0.85515468, 0.43869803],
        [0.9489325 , 0.47500036, 0.69271644, 0.78291682, 0.09097189],
        [0.80119116, 0.80302649, 0.29870696, 0.2989738 , 0.35722658]],

       [[0.65718898, 0.24558324, 0.79236134, 0.46982839, 0.85116803],
        [0.5043394 , 0.76706321, 0.23984608, 0.86035417, 0.14361975],
        [0.194876  , 0.67411862, 0.7346234 , 0.94957784, 0.86089822],
        [0.88466818, 0.78614794, 0.35598689, 0.11644415, 0.68143328]]])

### Acessando elementos específicos

In [5]:
# Acessando elementos de um ndarray de 1 dimensão
a1D

array([3, 7, 6, 4, 2, 9, 7, 3, 6, 1])

In [6]:
# nome_do_array[índice]
a1D[0]

3

In [7]:
a1D[2]

6

In [8]:
a1D[-1]

1

In [9]:
indices = [3, 0, -1] # Definindo uma lista com os índices que se deseja acessar
a1D[indices]

array([4, 3, 1])

In [10]:
# Acessando elementos de um ndarray de 2 dimensões
a2D

array([[24, 84, 82, 57, 76],
       [57, 77, 47, 55, 28],
       [49, 52, 44, 39, 47],
       [84, 90, 27, 43, 83]])

In [11]:
# nome_da_matriz[linha][coluna]
a2D[1][2]

47

In [12]:
a2D[3][4]

83

In [13]:
indice_lin = [0, 1, 2, 3]
indice_col = [0, 1, 2, 3]

a2D[indice_lin, indice_col]

array([24, 77, 44, 43])

In [14]:
indice_lin = [0, 1, 2, 3]
indice_col = [3, 2, 1, 0]

a2D[indice_lin, indice_col]

array([57, 47, 52, 84])

In [15]:
indice_lin = [3, 2, 1, 0]
indice_col = [3, 2, 1, 0]

a2D[indice_lin, indice_col]

array([43, 44, 77, 24])

In [16]:
a2D[:,[0,1,2,0]] 

array([[24, 84, 82, 24],
       [57, 77, 47, 57],
       [49, 52, 44, 49],
       [84, 90, 27, 84]])

In [17]:
a2D[:,[0,1,2,0]][[1, 0, 1, 0]]

array([[57, 77, 47, 57],
       [24, 84, 82, 24],
       [57, 77, 47, 57],
       [24, 84, 82, 24]])

In [18]:
a2D

array([[24, 84, 82, 57, 76],
       [57, 77, 47, 55, 28],
       [49, 52, 44, 39, 47],
       [84, 90, 27, 43, 83]])

In [19]:
a2D[[1, 0, 1, 0]][:,[0,1,2,0]] 

array([[57, 77, 47, 57],
       [24, 84, 82, 24],
       [57, 77, 47, 57],
       [24, 84, 82, 24]])

In [20]:
# Acessando elementos de um ndarray de 3 dimensões
a3D

array([[[0.88720697, 0.14172453, 0.68358888, 0.53132012, 0.58597368],
        [0.06332662, 0.00480406, 0.30022844, 0.33106264, 0.93174487],
        [0.80329166, 0.05535711, 0.19428014, 0.15125549, 0.03183321],
        [0.07259996, 0.69920108, 0.14796289, 0.05212782, 0.9861232 ]],

       [[0.89658827, 0.26275716, 0.36136653, 0.72448043, 0.73187594],
        [0.8340891 , 0.13870417, 0.23590704, 0.85515468, 0.43869803],
        [0.9489325 , 0.47500036, 0.69271644, 0.78291682, 0.09097189],
        [0.80119116, 0.80302649, 0.29870696, 0.2989738 , 0.35722658]],

       [[0.65718898, 0.24558324, 0.79236134, 0.46982839, 0.85116803],
        [0.5043394 , 0.76706321, 0.23984608, 0.86035417, 0.14361975],
        [0.194876  , 0.67411862, 0.7346234 , 0.94957784, 0.86089822],
        [0.88466818, 0.78614794, 0.35598689, 0.11644415, 0.68143328]]])

In [21]:
# nome_do_cubo[página][linha][coluna]
a3D[2][0][3]

0.46982838816447214

In [22]:
a3D[0][3][1]

0.6992010784295932

### Fatiamento (slicing)

In [23]:
# Array de 1 dimensão
a1D

array([3, 7, 6, 4, 2, 9, 7, 3, 6, 1])

In [24]:
a = a1D[1:5] # Índice 1 ao 4
a

array([7, 6, 4, 2])

In [25]:
b = a1D[0:6] # Índice 0 ao 5
b

array([3, 7, 6, 4, 2, 9])

In [26]:
c = a1D[:6] # Do início ao 5
c

array([3, 7, 6, 4, 2, 9])

In [27]:
d = a1D[::2] # Do início ao fim, com passo 2
d

array([3, 6, 2, 7, 6])

In [28]:
e = a1D[-1::-1] # Do final até o início
e

array([1, 6, 3, 7, 9, 2, 4, 6, 7, 3])

In [29]:
# Array de 2 dimensões
a2D

array([[24, 84, 82, 57, 76],
       [57, 77, 47, 55, 28],
       [49, 52, 44, 39, 47],
       [84, 90, 27, 43, 83]])

In [30]:
linha0 = a2D[0] # Todos os elementos da linha 0 - outra forma seria: linha0 = a2D[0,:]
linha0

array([24, 84, 82, 57, 76])

In [31]:
linha1 = a2D[1,:] # Todos os elementos da linha 1
linha1

array([57, 77, 47, 55, 28])

In [32]:
linha2 = a2D[2,1:4] # Linha 2, colunas 1, 2 e 3
linha2

array([52, 44, 39])

In [33]:
linha3 = a2D[:][3] # a2D[:] retorna toda a matriz, então de toda a matriz queremos a linha 3 a2D[:][3]
linha3

array([84, 90, 27, 43, 83])

In [34]:
coluna2 = a2D[:,2] # De todas as linhas, selecionar a coluna 2
coluna2

array([82, 47, 44, 27])

In [35]:
coluna3 = a2D[1:,3] # Da linha um até a última, selecionar a coluna 3
coluna3

array([55, 39, 43])

In [36]:
# Array de 3 dimensões
a3D

array([[[0.88720697, 0.14172453, 0.68358888, 0.53132012, 0.58597368],
        [0.06332662, 0.00480406, 0.30022844, 0.33106264, 0.93174487],
        [0.80329166, 0.05535711, 0.19428014, 0.15125549, 0.03183321],
        [0.07259996, 0.69920108, 0.14796289, 0.05212782, 0.9861232 ]],

       [[0.89658827, 0.26275716, 0.36136653, 0.72448043, 0.73187594],
        [0.8340891 , 0.13870417, 0.23590704, 0.85515468, 0.43869803],
        [0.9489325 , 0.47500036, 0.69271644, 0.78291682, 0.09097189],
        [0.80119116, 0.80302649, 0.29870696, 0.2989738 , 0.35722658]],

       [[0.65718898, 0.24558324, 0.79236134, 0.46982839, 0.85116803],
        [0.5043394 , 0.76706321, 0.23984608, 0.86035417, 0.14361975],
        [0.194876  , 0.67411862, 0.7346234 , 0.94957784, 0.86089822],
        [0.88466818, 0.78614794, 0.35598689, 0.11644415, 0.68143328]]])

In [37]:
# Acessando a página/face 1
face1 = a3D[1]
face1

array([[0.89658827, 0.26275716, 0.36136653, 0.72448043, 0.73187594],
       [0.8340891 , 0.13870417, 0.23590704, 0.85515468, 0.43869803],
       [0.9489325 , 0.47500036, 0.69271644, 0.78291682, 0.09097189],
       [0.80119116, 0.80302649, 0.29870696, 0.2989738 , 0.35722658]])

In [38]:
# Acessando uma parte da face1
subface1 = a3D[1,0:3, 1:4]
subface1

array([[0.26275716, 0.36136653, 0.72448043],
       [0.13870417, 0.23590704, 0.85515468],
       [0.47500036, 0.69271644, 0.78291682]])

In [39]:
linha2face0 = a3D[0,2] # outra forma: linha2face0 = a3D[0,2,:]
linha2face0

array([0.80329166, 0.05535711, 0.19428014, 0.15125549, 0.03183321])

In [40]:
a3D

array([[[0.88720697, 0.14172453, 0.68358888, 0.53132012, 0.58597368],
        [0.06332662, 0.00480406, 0.30022844, 0.33106264, 0.93174487],
        [0.80329166, 0.05535711, 0.19428014, 0.15125549, 0.03183321],
        [0.07259996, 0.69920108, 0.14796289, 0.05212782, 0.9861232 ]],

       [[0.89658827, 0.26275716, 0.36136653, 0.72448043, 0.73187594],
        [0.8340891 , 0.13870417, 0.23590704, 0.85515468, 0.43869803],
        [0.9489325 , 0.47500036, 0.69271644, 0.78291682, 0.09097189],
        [0.80119116, 0.80302649, 0.29870696, 0.2989738 , 0.35722658]],

       [[0.65718898, 0.24558324, 0.79236134, 0.46982839, 0.85116803],
        [0.5043394 , 0.76706321, 0.23984608, 0.86035417, 0.14361975],
        [0.194876  , 0.67411862, 0.7346234 , 0.94957784, 0.86089822],
        [0.88466818, 0.78614794, 0.35598689, 0.11644415, 0.68143328]]])

In [41]:
linha1todasfaces = a3D[:,1] # outra forma: linha1todasfaces = a3D[:,1,:]
linha1todasfaces

array([[0.06332662, 0.00480406, 0.30022844, 0.33106264, 0.93174487],
       [0.8340891 , 0.13870417, 0.23590704, 0.85515468, 0.43869803],
       [0.5043394 , 0.76706321, 0.23984608, 0.86035417, 0.14361975]])

In [42]:
coluna3todasfaces = a3D[:,:,3]
coluna3todasfaces

array([[0.53132012, 0.33106264, 0.15125549, 0.05212782],
       [0.72448043, 0.85515468, 0.78291682, 0.2989738 ],
       [0.46982839, 0.86035417, 0.94957784, 0.11644415]])

### Indexação com booleanos

In [43]:
a2D = np.random.randint(1, 501, (10, 8)) # Cria um ndarray de 4 linhas x 5 colunas com elementos entre 1 e 100
a2D

array([[381, 474, 404, 325, 211, 241,  10, 327],
       [287,  23, 371, 458, 227, 168, 485, 386],
       [438,  37, 343, 385, 317, 287, 250, 261],
       [109, 252, 124, 345, 318, 484, 313, 320],
       [114, 113, 116, 182, 142,  94,  71, 440],
       [337, 350, 413, 120, 287, 367, 329, 314],
       [431, 186, 136, 436, 236, 329, 202, 133],
       [190, 402,  47, 412,  79, 445, 353, 408],
       [490, 252, 400, 183, 481, 336, 133,  40],
       [259, 357, 275, 465, 358,  37,  96, 347]])

In [44]:
a2D >= 250

array([[ True,  True,  True,  True, False, False, False,  True],
       [ True, False,  True,  True, False, False,  True,  True],
       [ True, False,  True,  True,  True,  True,  True,  True],
       [False,  True, False,  True,  True,  True,  True,  True],
       [False, False, False, False, False, False, False,  True],
       [ True,  True,  True, False,  True,  True,  True,  True],
       [ True, False, False,  True, False,  True, False, False],
       [False,  True, False,  True, False,  True,  True,  True],
       [ True,  True,  True, False,  True,  True, False, False],
       [ True,  True,  True,  True,  True, False, False,  True]])

In [45]:
a2D[a2D >= 250]

array([381, 474, 404, 325, 327, 287, 371, 458, 485, 386, 438, 343, 385,
       317, 287, 250, 261, 252, 345, 318, 484, 313, 320, 440, 337, 350,
       413, 287, 367, 329, 314, 431, 436, 329, 402, 412, 445, 353, 408,
       490, 252, 400, 481, 336, 259, 357, 275, 465, 358, 347])

In [46]:
a2D.mean()

276.05

In [47]:
a2D[a2D <= a2D.mean()]

array([211, 241,  10,  23, 227, 168,  37, 250, 261, 109, 252, 124, 114,
       113, 116, 182, 142,  94,  71, 120, 186, 136, 236, 202, 133, 190,
        47,  79, 252, 183, 133,  40, 259, 275,  37,  96])